name: CI 
on: 
  push: 
    branches: ['main'] 
  workflow_dispatch: {}
jobs: 
  checkout-test: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/scripts
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v4 
      - uses: actions/setup-node@v1 
      - run: ./prepare.sh 
      - run: ./test.sh
